### ISSUE TITLE
Convert python script work on windows

### ISSUE THREAD

**Issue by CalumY** [MarcoFossati/projects-cluster#29]
I believe that originally the script was written to work on a Linux computer. When trying to run it on windows there have been a few issues with functions that are not on windows. These functions include:

- [x] Find replacement for 'ln -s'.
- [x] Find a solution for " 'mpirun' is not recognized as an internal or external command, operable program or batch file." error.
- [x] Find a solution for " 'pvpython' is not recognized as an internal or external command, operable program or batch file." error.
- [x] Find a solution for " Traceback (most recent call last):
  File "C:\Users\calum\Documents\4th Year Project\remeshing.py", line 747, in <module>
    currentFieldIndex = callAMRTechnique(currentRunDir, currentRunDir, su2, meshIter, meshesFolder, currentFieldIndex)
  File "C:\Users\calum\Documents\4th Year Project\remeshing.py", line 148, in callAMRTechnique
    cFI = globals()[str(Obj.remeshingTechnique.methodName) + "AMR"](Obj.meshes[meshIte], Obj.meshes[meshIte+1], Obj.remeshingTechnique, meshIte, solutionPath, meshesFolder, currentFieldIndex)
  File "C:\Users\calum\Documents\4th Year Project\remeshing.py", line 177, in gradientBasedAMR
    with open(fieldName + 'Gradient.csv', 'rb') as csvfile:
IOError: [Errno 2] No such file or directory: 'MachGradient.csv' " error.

**Comment by CalumY** [comment]
If the script is run through the ParaView python shell then 'pvpython' is imported so that error does not occur.

**Comment by CalumY** [comment]
Another option for removing the 'pvpython' error would be to comment out the line that it is called as I don't think it does anything. This line:

globals()[str(Obj.remeshingTechnique.methodName) + "Paraview"](Obj.remeshingTechnique, solutionPath, printPath)

This is used in the function: 

def callAMRTechnique(solutionPath, printPath, Obj, meshIte, meshesFolder, currentFieldIndex):

  cFI = currentFieldIndex
  
  #globals()[str(Obj.remeshingTechnique.methodName) + "Paraview"](Obj.remeshingTechnique, solutionPath, printPath)  
    
  cFI = globals()[str(Obj.remeshingTechnique.methodName) + "AMR"](Obj.meshes[meshIte], Obj.meshes[meshIte+1], Obj.remeshingTechnique, meshIte, solutionPath, meshesFolder, currentFieldIndex)
  
  return cFI

**Comment by CalumY** [comment]
'mpirun' and 'ln -s' issues sorted
